### PR TITLE
Adding Times tag support

### PR DESCRIPTION
**Pull request by pablopnn**
This PR contains:
+ Times tag support

Note: there are many changes because of code formatting, sorry.

### CODE REVIEW

**Comment by papa-pep** [comment]
Looks like pablopnn beat me to adding Times tag support.  Thanks!

**Comment by bmancini55** [comment]
My bad, this pull request slipped through the cracks!  @pablopnn would you might resubmitting with cleaned up whitespace so it's consistent with the rest of the repo?  The rest of the repo uses 2-space tabs.

Thanks!

**Comment by pablopnn** [comment]
I added [.editorconfig](http://editorconfig.org/), makes collaboration easier between IDEs. Take a look if this way works for you. Thanks

**Comment by bmancini55** [comment]
That definitely works!  Much appreciated.  Merging pull request now.

**Pull request merged**
